import type { OpenAPIV3 } from "openapi-types";
import { openApiSchemas } from "./openapi.schemas.js";

const jsonContent = (schemaName: keyof typeof openApiSchemas) => ({
  "application/json": {
    schema: {
      $ref: `#/components/schemas/${schemaName}`,
    },
  },
});

export const openApiDocument: OpenAPIV3.Document = {
  openapi: "3.0.3",
  info: {
    title: "NO CHEAT ERP API",
    version: "1.0.0",
    description:
      "Sunshine Corporation NO CHEAT ERP API. Future business operations are registered under /api/v1. Versioned API requests accept X-Correlation-ID and echo it in the response; when absent, the API generates a unique correlation ID.",
  },
  servers: [
    {
      url: "http://localhost:4000",
      description: "Local development server",
    },
  ],
  tags: [
    {
      name: "System",
      description: "Infrastructure and application health checks.",
    },
  ],
  paths: {
    "/api/v1": {
      description:
        "Version 1 API namespace. Future module operations are registered below this root.",
    },
    "/health": {
      get: {
        operationId: "getApplicationHealth",
        tags: ["System"],
        summary: "Check API liveness",
        description:
          "Confirms that the Express API process is running and able to respond.",
        responses: {
          "200": {
            description: "The API is running.",
            content: jsonContent("HealthResponse"),
          },
        },
      },
    },
    "/health/db": {
      get: {
        operationId: "getDatabaseHealth",
        tags: ["System"],
        summary: "Check PostgreSQL connectivity",
        description:
          "Confirms database connectivity through the repository and Prisma health flow.",
        responses: {
          "200": {
            description: "PostgreSQL is reachable.",
            content: jsonContent("DatabaseHealthResponse"),
          },
          "500": {
            $ref: "#/components/responses/InternalServerError",
          },
        },
      },
    },
  },
  components: {
    schemas: openApiSchemas,
    parameters: {
      CorrelationId: {
        name: "X-Correlation-ID",
        in: "header",
        required: false,
        description:
          "Optional request correlation ID. When supplied it is echoed in the response; otherwise the API generates a unique ID.",
        schema: {
          type: "string",
        },
      },
    },
    headers: {
      CorrelationId: {
        description:
          "The request correlation ID supplied by the client or generated by the API.",
        schema: {
          type: "string",
        },
      },
    },
    responses: {
      ValidationError: {
        description: "Request validation failed.",
        headers: {
          "X-Correlation-ID": {
            $ref: "#/components/headers/CorrelationId",
          },
        },
        content: jsonContent("ValidationErrorResponse"),
      },
      NotFound: {
        description: "The requested API resource was not found.",
        headers: {
          "X-Correlation-ID": {
            $ref: "#/components/headers/CorrelationId",
          },
        },
        content: jsonContent("StandardErrorResponse"),
      },
      InternalServerError: {
        description: "An unexpected server error occurred.",
        content: jsonContent("StandardErrorResponse"),
      },
    },
  },
};
